# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_flask',
                'doc_host': 'https://aloiswirth.github.io',
                'git_url': 'https://github.com/aloiswirth/nbdev_flask',
                'lib_path': 'nbdev_flask'},
  'syms': { 'nbdev_flask.nbdev_docs_flask': { 'nbdev_flask.nbdev_docs_flask.ready': ( 'nbdev_flask.html#ready',
                                                                                      'nbdev_flask/nbdev_docs_flask.py')}}}
