# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_nbdev_flask.ipynb.

# %% auto 0
__all__ = ['app', 'ready']

# %% ../nbs/00_nbdev_flask.ipynb 2
from flask import Flask

# %% ../nbs/00_nbdev_flask.ipynb 3
app = Flask(__name__)   # create a Flask app

# %% ../nbs/00_nbdev_flask.ipynb 4
@app.route('/')
def ready():
    return "The service is running!"

# %% ../nbs/00_nbdev_flask.ipynb 6
if __name__ == '__main__':
    app.run(host='127.0.0.1', port=54001)  # run the app
